import 'package:get/get.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'app_name'           : 'Clinic',
      'settings_text'      : 'Settings',
      'welcome_text'       : 'Hello, Welcome Aboard.',
      'login'              : 'LOGIN',
      'username'           : 'Username',
      'password'           : 'Password',
      'privacy1'           : 'I accept terms of the offer of ',
      'privacy2'           : 'the privacy policy',
      'loginBtn'           : 'Log In',
      'signup'             : 'Sign Up',
      'signupText1'        : "Don't have an account?",
      'signupText2'        : ' Sign up',
      'signupBtn'          : 'Sign Up',
      'firstname'          : 'First Name',
      'lastname'           : 'Last Name',
      'confirmPassword'    : 'Confirm Password', 
      'phonenumber'        : 'Phone Number',
      'gender'             : 'Gender',
      'address'            : 'Address',
      'bio'                : 'Bio',
      'usertype'           : 'User Type',
      'occupation'         : 'Occupation',
      'socialLink1'        : 'Social Media Link 1',
      'socialLink2'        : 'Social Media Link 2',
      'socialLink3'        : 'Social Media Link 3',
      'rememberMe'         : 'Remember Me',
      'forgotPassword'     : 'Forgot Password?',
      'oldPassowrd'        : 'Old Passowrd',
      'newPassword'        : 'New Password',
      'changePassword'     : 'Change Password',
      'email'              : 'Email',
      'enterEmail'         : 'Enter your email to reset your password',
      'loginWithGoogle'    : 'Sign in with Google',
      'dob'                : 'D.O.B.',
      'submit'             : 'Submit',
      'note'               : 'Note',
      'goToLogin'          : 'Go To Login',
      'sendResetLink'      : 'Send Reset Link',
      'services'           : ' Services',
      'ourDoctors'         : 'Our Doctors',
    },
    'de_DE': {
      'app_name'           : 'Clinic',
      'settings_text'      : 'Settings',
      'welcome_text'       : 'Hello, Welcome Aboard.',
      'login'              : 'LOGIN',
      'username'           : 'Username',
      'password'           : 'Password',
      'privacy1'           : 'I accept terms of the offer of ',
      'privacy2'           : 'the privacy policy',
      'loginBtn'           : 'Log In',
      'signup'             : 'Sign Up',
      'signupText1'        : "Don't have an account?",
      'signupText2'        : 'Sign up',
      'signupBtn'          : 'Sign Up',
      'firstname'          : 'First Name',
      'lastname'           : 'Last Name',
      'confirmPassword'    : 'Confirm Password', 
      'phonenumber'        : 'Phone Number',
      'gender'             : 'Gender',
      'address'            : 'Address',
      'bio'                : 'Bio',
      'usertype'           : 'User Type',
      'occupation'         : 'Occupation',
      'socialLink1'        : 'Social Media Link 1',
      'socialLink2'        : 'Social Media Link 2',
      'socialLink3'        : 'Social Media Link 3',
      'rememberMe'         : 'Remember Me',
      'forgotPassword'     : 'Forgot Password?',
      'oldPassowrd'        : 'Old Passowrd',
      'newPassword'        : 'New Password',
      'changePassword'     : 'Change Password',
      'email'              : 'Email',
      'enterEmail'         : 'Enter your email to reset your password',
      'loginWithGoogle'    : 'Sign in with Google',
      'dob'                : 'D.O.B.',
      'submit'             : 'Submit',
      'note'               : 'Note',
      'goToLogin'          : 'Go To Login',
      'sendResetLink'      : 'Send Reset Link',
      'services'           : ' Services',
      'ourDoctors'         : 'Our Doctors',
    },
  };
}